// Content: chaos events.
export const EVENTS = [
  { id: 'cow_runs',       copy: 'the bread cow ran off. -50% rate for 30s',           kind: 'debuff',      duration: 30000, mult: 0.5 },
  { id: 'tinyclaw_help',  copy: 'tinyclaw stopped by and helped knead. x5 rate for 15s', kind: 'buff',     duration: 15000, mult: 5 },
  { id: 'tip',            copy: 'a customer tipped. unclear why. +250',                kind: 'instant',     amount: 250 },
  { id: 'oven_hot',       copy: 'the oven runs hot. x2 rate for 20s',                 kind: 'buff',        duration: 20000, mult: 2 },
  { id: 'tinyclaw_steal', copy: 'tinyclaw appeared and ate 10% of the stockpile',     kind: 'instant_pct', factor: -0.10 },
  { id: 'wizard_chant',   copy: 'the wizard chanted something. +500',                 kind: 'instant',     amount: 500 },
  { id: 'cow_returns',    copy: 'the bread cow returned with friends. x3 for 25s',    kind: 'buff',        duration: 25000, mult: 3 },
  { id: 'mouse',          copy: 'a mouse. -100. unsurprising.',                       kind: 'instant',     amount: -100 },
  { id: 'union',          copy: 'the apprentices unionized. wages up. -25% for 40s',  kind: 'debuff',      duration: 40000, mult: 0.75 },
  { id: 'happy_hour',     copy: 'happy hour. x4 rate for 10s. brief but loud.',       kind: 'buff',        duration: 10000, mult: 4 },
  { id: 'transmute',      copy: 'the wizard transmuted lead into bread. +1000',       kind: 'instant',     amount: 1000 },
  { id: 'factory_break',  copy: 'the factory broke a belt. -10% rate for 60s',        kind: 'debuff',      duration: 60000, mult: 0.9 },
  { id: 'tinyclaw_drop',  copy: 'tinyclaw misjudged a swoop. dropped 200. yours now.', kind: 'instant',    amount: 200 },
  { id: 'sourdough',      copy: 'the starter is unusually active. x2 for 30s',         kind: 'buff',        duration: 30000, mult: 2 },
  { id: 'golden_storm',   copy: 'a storm of golden pumpernickels. x10 for 10s',         kind: 'buff',        duration: 10000, mult: 10 },
  { id: 'wizard_summon',  copy: 'the wizard summoned a baguette demon. +2000',          kind: 'instant',     amount: 2000 },
  { id: 'bread_riot',     copy: 'the apprentices are unionizing harder. -30% for 40s',  kind: 'debuff',      duration: 40000, mult: 0.7 },
  { id: 'citadel_siege',  copy: 'the citadel is besieged. defense rations. x4 for 20s', kind: 'buff',        duration: 20000, mult: 4 },
  { id: 'flour_dust',     copy: 'a flour dust explosion. +5% to your bank.',            kind: 'instant_pct', factor: 0.05 },
  { id: 'cosmic_align',   copy: 'cosmic alignment. wizards weep. x8 for 8s',            kind: 'buff',        duration: 8000,  mult: 8 },
  { id: 'strawberry_cow', copy: 'a strawberry cow wandered in. she winked. x5 for 14s', kind: 'buff',        duration: 14000, mult: 5 },
];
