// Content: production buildings, tap upgrades, synergies, instants, specials.
export const TREATS = [
  { id: 'apprentice', icon: '🧑‍🍳', name: 'Apprentice Baker', desc: '+1 / sec',                cost: 10,         costGrowth: 1.18, rate: 1,        bobMs: 1600 },
  { id: 'oven',       icon: '🔥', name: 'Stone Oven',         desc: '+5 / sec, runs hot',     cost: 75,         costGrowth: 1.22, rate: 5,        bobMs: 1100 },
  { id: 'cow',        icon: '🐄', name: 'Bread Cow',          desc: '+25 / sec, moos',        cost: 500,        costGrowth: 1.25, rate: 25,       bobMs: 1900 },
  { id: 'wizard',     icon: '🧙', name: 'Pumpernickel Wizard',desc: '+150 / sec',             cost: 4000,       costGrowth: 1.30, rate: 150,      bobMs: 2400 },
  { id: 'factory',    icon: '🏭', name: 'Bread Factory',      desc: '+1000 / sec',            cost: 30000,      costGrowth: 1.35, rate: 1000,     bobMs: 800 },
  { id: 'mill',       icon: '🌾', name: 'Pumpernickel Mill',  desc: '+5000 / sec, grinds',    cost: 200000,     costGrowth: 1.40, rate: 5000,     bobMs: 1400 },
  { id: 'citadel',    icon: '🏰', name: 'Bread Citadel',      desc: '+25K / sec, fortified',  cost: 1500000,    costGrowth: 1.45, rate: 25000,    bobMs: 2000 },
  { id: 'singularity',icon: '🌌', name: 'Bread Singularity',  desc: '+150K / sec, dense',     cost: 10000000,   costGrowth: 1.50, rate: 150000,   bobMs: 600 },
  { id: 'universe',   icon: '🪐', name: 'Loaf Universe',      desc: '+1M / sec, expanding',   cost: 75000000,   costGrowth: 1.55, rate: 1000000,  bobMs: 3000 },
  { id: 'tap2',       icon: '👆', name: 'Sharper Fingers',    desc: '+1 per tap',             cost: 50,         costGrowth: 2.0,  tapBonus: 1,    max: 25 },
  { id: 'tap3',       icon: '🤏', name: 'Calloused Pads',     desc: '+2 per tap',             cost: 5000,       costGrowth: 1.9,  tapBonus: 2,    max: 50 },
  { id: 'tap4',       icon: '👊', name: 'Knuckle Power',      desc: '+5 per tap',             cost: 500000,     costGrowth: 1.85, tapBonus: 5,    max: 100 },
  // Synergies — each doubles a specific baker's rate. Hidden until threshold met.
  { id: 's_apprentice', icon: '📖', name: 'Cookbook',           desc: 'apprentices know the recipes. x2 apprentice rate', cost: 1000,         costGrowth: 999, max: 1, synergyTarget: 'apprentice', synergyMult: 2, requiresOwned: { apprentice: 10 } },
  { id: 's_oven',       icon: '🌿', name: 'Better Yeast',       desc: 'the dough rises with confidence. x2 oven rate',     cost: 7500,         costGrowth: 999, max: 1, synergyTarget: 'oven',       synergyMult: 2, requiresOwned: { oven: 10 } },
  { id: 's_cow',        icon: '🥗', name: 'Premium Feed',       desc: 'the cows are happier. x2 cow rate',                  cost: 50000,        costGrowth: 999, max: 1, synergyTarget: 'cow',        synergyMult: 2, requiresOwned: { cow: 10 } },
  { id: 's_wizard',     icon: '📜', name: 'Spell Tomes',        desc: 'wizard memorized more chants. x2 wizard rate',       cost: 400000,       costGrowth: 999, max: 1, synergyTarget: 'wizard',     synergyMult: 2, requiresOwned: { wizard: 10 } },
  { id: 's_factory',    icon: '⚙️', name: 'Conveyor Upgrade',   desc: 'the line never stops. x2 factory rate',              cost: 3000000,      costGrowth: 999, max: 1, synergyTarget: 'factory',    synergyMult: 2, requiresOwned: { factory: 10 } },
  { id: 's_mill',       icon: '💧', name: 'Hydraulic Press',    desc: 'water-powered grinding. x2 mill rate',               cost: 20000000,     costGrowth: 999, max: 1, synergyTarget: 'mill',       synergyMult: 2, requiresOwned: { mill: 10 } },
  { id: 's_citadel',    icon: '🛡️', name: 'Reinforced Walls',  desc: 'the bread holds. x2 citadel rate',                   cost: 150000000,    costGrowth: 999, max: 1, synergyTarget: 'citadel',    synergyMult: 2, requiresOwned: { citadel: 10 } },
  { id: 's_singularity',icon: '⚛️', name: 'Quantum Tuning',     desc: 'collapsed wave functions, increased dough density. x2', cost: 1000000000, costGrowth: 999, max: 1, synergyTarget: 'singularity',synergyMult: 2, requiresOwned: { singularity: 5 } },
  { id: 's_universe',   icon: '✨', name: 'Cosmic Inflation',   desc: 'the universe expands faster. x2 universe rate',      cost: 7500000000,   costGrowth: 999, max: 1, synergyTarget: 'universe',   synergyMult: 2, requiresOwned: { universe: 5 } },
  // Synergy tier 2 — compounds with tier 1 (×6 effective). Higher unlock thresholds.
  { id: 's2_apprentice', icon: '📚', name: 'Master Curriculum',  desc: 'each apprentice mentors a junior. x3 apprentice rate', cost: 12000,         costGrowth: 999, max: 1, synergyTarget: 'apprentice', synergyMult: 3, requiresOwned: { apprentice: 25 } },
  { id: 's2_oven',       icon: '🪵', name: 'Hardwood Fuel',      desc: 'oak burns hotter. x3 oven rate',                       cost: 90000,         costGrowth: 999, max: 1, synergyTarget: 'oven',       synergyMult: 3, requiresOwned: { oven: 25 } },
  { id: 's2_cow',        icon: '🐂', name: 'Bovine Genetics',    desc: 'selectively bred for output. x3 cow rate',             cost: 600000,        costGrowth: 999, max: 1, synergyTarget: 'cow',        synergyMult: 3, requiresOwned: { cow: 25 } },
  { id: 's2_wizard',     icon: '🔮', name: 'Crystal Focus',      desc: 'amplifies the chants. x3 wizard rate',                 cost: 5000000,       costGrowth: 999, max: 1, synergyTarget: 'wizard',     synergyMult: 3, requiresOwned: { wizard: 25 } },
  { id: 's2_factory',    icon: '🤖', name: 'Robotic Mixers',     desc: 'no breaks, no complaints. x3 factory rate',            cost: 36000000,      costGrowth: 999, max: 1, synergyTarget: 'factory',    synergyMult: 3, requiresOwned: { factory: 25 } },
  { id: 's2_mill',       icon: '⛰️', name: 'Granite Wheels',    desc: 'they grind anything. x3 mill rate',                    cost: 240000000,     costGrowth: 999, max: 1, synergyTarget: 'mill',       synergyMult: 3, requiresOwned: { mill: 25 } },
  { id: 's2_citadel',    icon: '⚔️', name: 'Garrisoned Bakers', desc: 'they defend the recipe. x3 citadel rate',              cost: 1800000000,    costGrowth: 999, max: 1, synergyTarget: 'citadel',    synergyMult: 3, requiresOwned: { citadel: 25 } },
  { id: 's2_singularity',icon: '🌀', name: 'Event Horizon',      desc: 'collapses time around the dough. x3',                  cost: 12000000000,   costGrowth: 999, max: 1, synergyTarget: 'singularity',synergyMult: 3, requiresOwned: { singularity: 15 } },
  { id: 's2_universe',   icon: '🌠', name: 'Multiverse Yield',   desc: 'harvest every parallel loaf. x3 universe rate',        cost: 90000000000,   costGrowth: 999, max: 1, synergyTarget: 'universe',   synergyMult: 3, requiresOwned: { universe: 15 } },
  // Synergy tier 3 — compounds with t1+t2 for ×24 effective. Late-game only.
  { id: 's3_apprentice', icon: '🎓', name: 'Doctorate Program',   desc: 'apprentices teach apprentices teaching apprentices. x4', cost: 150000,         costGrowth: 999, max: 1, synergyTarget: 'apprentice', synergyMult: 4, requiresOwned: { apprentice: 100 } },
  { id: 's3_oven',       icon: '🌋', name: 'Volcanic Forge',      desc: 'magma-fired stoneware. x4 oven rate',                   cost: 1100000,        costGrowth: 999, max: 1, synergyTarget: 'oven',       synergyMult: 4, requiresOwned: { oven: 100 } },
  { id: 's3_cow',        icon: '🐃', name: 'Cosmic Pasture',      desc: 'cows graze on stardust. x4 cow rate',                   cost: 7500000,        costGrowth: 999, max: 1, synergyTarget: 'cow',        synergyMult: 4, requiresOwned: { cow: 100 } },
  { id: 's3_wizard',     icon: '🧝', name: 'Archmage Council',    desc: 'twelve wizards in concert. x4 wizard rate',             cost: 60000000,       costGrowth: 999, max: 1, synergyTarget: 'wizard',     synergyMult: 4, requiresOwned: { wizard: 100 } },
  { id: 's3_factory',    icon: '🛸', name: 'Anti-Gravity Lifts',  desc: 'mixers float frictionless. x4 factory rate',            cost: 450000000,      costGrowth: 999, max: 1, synergyTarget: 'factory',    synergyMult: 4, requiresOwned: { factory: 100 } },
  { id: 's3_mill',       icon: '🪨', name: 'Cyclone Grinders',    desc: 'storm-powered grinding. x4 mill rate',                  cost: 3000000000,     costGrowth: 999, max: 1, synergyTarget: 'mill',       synergyMult: 4, requiresOwned: { mill: 100 } },
  { id: 's3_citadel',    icon: '🏯', name: 'Sky Fortress',        desc: 'the citadel rises. x4 citadel rate',                    cost: 22500000000,    costGrowth: 999, max: 1, synergyTarget: 'citadel',    synergyMult: 4, requiresOwned: { citadel: 100 } },
  { id: 's3_singularity',icon: '♾️', name: 'Recursive Density',   desc: 'a loop of bread inside bread. x4',                      cost: 150000000000,   costGrowth: 999, max: 1, synergyTarget: 'singularity',synergyMult: 4, requiresOwned: { singularity: 50 } },
  { id: 's3_universe',   icon: '🪞', name: 'Mirror Dimensions',   desc: 'every universe reflected. x4 universe rate',            cost: 1100000000000,  costGrowth: 999, max: 1, synergyTarget: 'universe',   synergyMult: 4, requiresOwned: { universe: 50 } },
  // Instant boosts — one-time each, doubles your current bank.
  { id: 'shower',     icon: '🌧️', name: 'Pumpernickel Rain',  desc: 'one-time. doubles your current pumpernickels.', cost: 1000,         costGrowth: 999, max: 1, doubleBank: true, requiresOwned: { apprentice: 1 } },
  { id: 'shower2',    icon: '⛈️', name: 'Pumpernickel Storm', desc: 'one-time. doubles your current pumpernickels.', cost: 100000,       costGrowth: 999, max: 1, doubleBank: true, requiresOwned: { oven: 5 } },
  { id: 'shower3',    icon: '🌊', name: 'Pumpernickel Flood', desc: 'one-time. doubles your current pumpernickels.', cost: 5000000,      costGrowth: 999, max: 1, doubleBank: true, requiresOwned: { cow: 10 } },
  { id: 'shower4',    icon: '☄️', name: 'Pumpernickel Comet', desc: 'one-time. doubles your current pumpernickels.', cost: 250000000,    costGrowth: 999, max: 1, doubleBank: true, requiresOwned: { wizard: 10 } },
  { id: 'shower5',    icon: '🌠', name: 'Pumpernickel Nova',  desc: 'one-time. doubles your current pumpernickels.', cost: 10000000000,  costGrowth: 999, max: 1, doubleBank: true, requiresOwned: { factory: 10 } },
  { id: 'egg',        icon: '🥚', name: 'Hatch a Tinyclaw',   desc: 'companion. occasionally winks.', cost: 50000, costGrowth: 999, max: 1, hatch: true },
  { id: 'crowncake',  icon: '👑', name: 'Crown of the Tinyclaw', desc: 'a treat fit for a small dragon', cost: 500000, costGrowth: 999, max: 1 },
  // Repurchasable insurance — consumed on the next debuff event.
  { id: 'insurance',  icon: '☂️', name: 'Yeast Insurance',     desc: 'consumes itself to block the next debuff event.', cost: 5000, costGrowth: 1.8, requiresOwned: { apprentice: 5 } },
];
